### ISSUE TITLE
Use redis pipeline for moving and deleting message

### ISSUE THREAD

**Issue by faineance** [networklocum/redis-manager#6]
eg: http://mattcamilli.com/glory-of-redis-pipelines.html

**Comment by Manoj-nathwani** [comment]
![yup](http://gif.co/t9aD.gif)

**Comment by Manoj-nathwani** [comment]
https://github.com/networklocum/redis-manager/commit/0dd10e68c871b74a79adad91b1c0cd4b46417fdf
